version: '3'

services:
  db:
    image: mongo:latest
    container_name: mongodb
    hostname: mongodb
  web_app:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      - MONGO_URL=mongodb://mongodb:27017/
